/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        bg: 'var(--bg)',
        card: 'var(--card)',
        surface: 'var(--surface)',
        tertiary: 'var(--tertiary)',
        text: 'var(--text)',
        muted: 'var(--muted)',
        hint: 'var(--hint)',
        'border-default': 'var(--border)',
        'border-strong': 'var(--border-strong)',
        info: 'var(--info)',
        'info-bg': 'var(--info-bg)',
        'info-border': 'var(--info-border)',
        success: 'var(--success)',
        'success-bg': 'var(--success-bg)',
        'success-border': 'var(--success-border)',
        warn: 'var(--warn)',
        'warn-bg': 'var(--warn-bg)',
        'warn-border': 'var(--warn-border)',
        danger: 'var(--danger)',
        'danger-bg': 'var(--danger-bg)',
        'danger-border': 'var(--danger-border)',
        purple: 'var(--purple)',
        'purple-bg': 'var(--purple-bg)',
        'purple-border': 'var(--purple-border)',
        teal: 'var(--teal)',
        'teal-bg': 'var(--teal-bg)',
        'teal-border': 'var(--teal-border)',
      },
      borderRadius: {
        sm: 'var(--radius-sm)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
      },
      boxShadow: {
        sm: 'var(--shadow-sm)',
        md: 'var(--shadow-md)',
        lg: 'var(--shadow-lg)',
      },
      fontSize: {
        caption:  ['11px', { lineHeight: '1.4' }],
        meta:     ['12px', { lineHeight: '1.4' }],
        'body-sm':['13px', { lineHeight: '1.4' }],
        body:     ['14px', { lineHeight: '1.5' }],
        h3:       ['15px', { lineHeight: '1.3', letterSpacing: '-0.01em', fontWeight: '500' }],
        h2:       ['18px', { lineHeight: '1.3', letterSpacing: '-0.01em', fontWeight: '500' }],
        h1:       ['24px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '500' }],
        stat:     ['26px', { lineHeight: '1.05', letterSpacing: '-0.01em', fontWeight: '500' }],
        eyebrow:  ['11px', { lineHeight: '1.4', letterSpacing: '0.08em', fontWeight: '600' }],
      },
      letterSpacing: {
        eyebrow: '0.08em',
        data: '0.04em',
      },
      fontFamily: {
        sans: [
          '-apple-system',
          'BlinkMacSystemFont',
          '"Segoe UI"',
          'Roboto',
          'Helvetica',
          'Arial',
          'sans-serif',
        ],
        arabic: [
          '"Kanz al-Marjaan"',
          '"Geeza Pro"',
          '"Segoe UI"',
          'Tahoma',
          'Arial',
          'sans-serif',
        ],
      },
    },
  },
  plugins: [],
};
